name = "solana-rpc-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
PROXY_BASE_URL = "https://solana-rpc-proxy.dharadarsh0.workers.dev"
DISCORD_GUILD_ID = "1531347878906302484"
REGISTERED_ROLE_ID = "1531669950819733575"
SIGNUP_CHANNEL_ID = "1532423294354063410"
SUBSCRIPTION_CHANNEL_ID = "1531347878906302487"
MERCHANT_WALLET = "pt6Ws1FMbdrLbUZqKooediS8mu6SNvDJodzXUx6ypak"

# DISCORD_BOT_TOKEN is set via wrangler secret
# HELIUS_API_KEY is set via wrangler secret
